name: CI Pipeline
<<<<<<< HEAD

=======
 
>>>>>>> ab650946eab44a5f6bc59b2eb9ee6c21ad361046
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
<<<<<<< HEAD

jobs:
  test:
    name: Automaattestid
    runs-on: ubuntu-latest

    steps:
      - name: Lae kood alla
        uses: actions/checkout@v4

      - name: Paigalda Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Paigalda sõltuvused
        run: npm install

      - name: Käivitame rakenduse
        run: node src/server.js &

      - name: Oota kuni server käivitub
        run: sleep 3

      - name: Käivitame testid
        run: node src/test.js
=======
 
jobs:
  test: Automaattestid
  runs-on: ubuntu-latest
  steps:
    - name: Lae kood alla
    - uses: actions/checkout@v4
 
    - name: Paigalda Node.js
    uses: actions/setup-node@v4
    with:
      node-version: '20'
   
    - name: Paigalda sõltuvused
    run: npm install
 
    - name: Käivitame rakenduse
    run: node src/server.js &
 
    - name: Oota kuni server käivitub
    run: sleep 3
 
    - name: Käivitame testid
    run: node *TESTID*
>>>>>>> ab650946eab44a5f6bc59b2eb9ee6c21ad361046
